name: Build ESPHome Binary

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Compile ESPHome Binary
        run: |
          esphome compile irobot.yaml

      - name: Upload Firmware Binary
        uses: actions/upload-artifact@v4
        with:
          name: roomba-firmware
          path: .esphome/build/irobot/.pioenvs/irobot/firmware*.bin
